version: '3.8'

services:
  king-12:
    image: david-12
    build: .
    ports:
      - '6006:3000'
    environment:
      - MONGODB_URI:'mongodb://mongodb:27017/transactionhistory'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
